export default {
  pages: [
    'pages/index/index',
    'pages/cross-share/message/index',
    'pages/cross-share/file/index',
    'pages/profile/index',
    'pages/login/index',
    'pages/json-formatter/index',
    'pages/calendar/index',
    'pages/key-generator/index',
    'pages/ocr/index',
    'pages/http-client/index',
    'pages/asr/index',
    'pages/change-password/index',
    'pages/help/index',
    'pages/openclaw/index',
  ],
  subPackages: [],
  preloadRule: {},
  window: {
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#0F172A',
    navigationBarTitleText: '工具箱',
    navigationBarTextStyle: 'white',
    backgroundColor: '#0F172A',
  },
  tabBar: {
    color: '#64748B',
    selectedColor: '#3B82F6',
    backgroundColor: '#1E293B',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '工具',
        iconPath: 'assets/icons/tool.png',
        selectedIconPath: 'assets/icons/tool-active.png',
      },
      {
        pagePath: 'pages/cross-share/message/index',
        text: '消息',
        iconPath: 'assets/icons/message.png',
        selectedIconPath: 'assets/icons/message-active.png',
      },
      {
        pagePath: 'pages/cross-share/file/index',
        text: '文件',
        iconPath: 'assets/icons/file.png',
        selectedIconPath: 'assets/icons/file-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/icons/profile.png',
        selectedIconPath: 'assets/icons/profile-active.png',
      },
    ],
  },
}
